server:
  port: 8090

spring:
  application:
    name: hogar360-casas-ms
  datasource:
    url: jdbc:mysql://localhost/hogar360_casas
    username: ${user}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update